# Generated by Django 4.1.7 on 2023-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('speed', models.FloatField()),
                ('overspeeding', models.BooleanField()),
                ('link', models.URLField(blank=True, default=None)),
            ],
        ),
    ]
