# Generated by Django 4.1.7 on 2023-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.URLField(blank='', default=None),
        ),
    ]
